from pathlib import Path
import torch


DATA_PATH = Path('../data')
TIMIT_PATH = DATA_PATH / 'timit'

TRAIN_PATH = DATA_PATH / 'train'
TRAIN_RAW_PATH = TRAIN_PATH / 'raw'
TRAIN_PHONEMES_PATH = TRAIN_PATH / 'phonemes'
TRAIN_AUGMENTED_PATH = TRAIN_PATH / 'augmented'
TRAIN_AUGMENTED_FRAMES_PATH = TRAIN_PATH / 'augmented_frames'

TEST_PATH = DATA_PATH / 'test'
TEST_RAW_PATH = TEST_PATH / 'raw'
TEST_RAW_FRAMES_PATH = TEST_PATH / 'raw_frames'

VAL_PATH = DATA_PATH / 'val'
VAL_RAW_PATH = VAL_PATH / 'raw'
VAL_RAW_FRAMES_PATH = VAL_PATH / 'raw_frames'


SAMPLE_RATE = 16000
VAL_PERCENTAGE = 0.2
FRAME_LENGTH = 25 # in ms
STRIDE = 10 # in ms
SPECGRAM_HOP_LENGTH = 128
SPECGRAM_N_MELS = 64
CUDA0 = torch.device('cuda:0')
AUGMENT_LERP_N_SAMPLES = 2
AUGMENT_TOTAL_RECORDS = 1000