from pathlib import Path
import torch


DATA_PATH = Path('../data')
TIMIT_PATH = DATA_PATH / 'timit'
TRAIN_PATH = DATA_PATH / 'train'
TEST_PATH = DATA_PATH / 'test'
VAL_PATH = DATA_PATH / 'val'

CUDA0 = torch.device('cuda:0')
VAL_PERCENTAGE = 0.2
AUGMENT_DATASET = True
FRAME_LENGTH = 25  # in ms
FRAME_RESOLUTION = 4
STRIDE = 10  # in ms
N_MELS = 89
SAMPLE_RATE = 16000

# semi-constants (depend on previous constants)
SAMPLES_PER_FRAME = int(SAMPLE_RATE / 1000 * FRAME_LENGTH)
SAMPLES_PER_STRIDE = int(SAMPLE_RATE / 1000 * STRIDE)
FBANK_FRAME_LENGTH = FRAME_LENGTH // FRAME_RESOLUTION
FBANK_STRIDE = STRIDE // FRAME_RESOLUTION
